#@formatter:off
name: test_prj_ivan
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  collection: ^1.18.0
  connectivity_plus: ^6.0.3
  crypto: ^3.0.3
  cupertino_icons: ^1.0.8
  dio: ^5.5.0+1
  dio_cache_interceptor: ^3.5.0
  encrypt: ^5.0.3
  firebase_auth: ^5.1.3
  firebase_core: ^3.3.0
  firebase_messaging: ^15.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.1.0
  flutter_jailbreak_detection: ^1.10.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.1
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.5
  freezed_annotation: ^2.4.4
  gap: ^3.0.1
  get_it: ^7.7.0
  go_router: ^14.2.1
  google_sign_in: ^6.2.1
  internet_connection_checker: ^1.0.0+1
  intl: ^0.19.0
  intl_utils: ^2.8.7
  json_annotation: ^4.9.0
  loader_overlay: ^4.0.1
  logger: ^2.4.0
  path_provider: ^2.1.3
  pinput: ^5.0.0
  pretty_dio_logger: ^1.4.0
  retry: ^3.1.2
  shared_preferences: ^2.2.3
  sign_in_with_apple: ^6.1.1
  theme_tailor_annotation: 3.0.1

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.11
  flutter_flavorizr: ^2.2.3
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  import_sorter: ^4.6.0
  json_serializable: ^6.8.0
  mockito: ^5.4.4
  test: ^1.25.2
  theme_tailor: 3.0.1

flutter:
  uses-material-design: true
  

    # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/launcher_icons/
    - assets/icons/
    #   - images/a_dot_ham.jpeg


    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"

  flavors:
    dev:
      app:
        name: "Test Prj Ivan Dev"

      android:
        applicationId: "com.onix.flutter.firebase.auth.test.test_prj_ivan.dev"
        icon: "flavor_assets/dev/launcher_icons/ic_launcher.png"

      ios:
        bundleId: "com.onix.flutter.firebase.auth.test.test_prj_ivan.dev"
        icon: "flavor_assets/dev/launcher_icons/ic_launcher.png"


    prod:
      app:
        name: "Test Prj Ivan"

      android:
        applicationId: "com.onix.flutter.firebase.auth.test.test_prj_ivan"
        icon: "flavor_assets/prod/launcher_icons/ic_launcher.png"

      ios:
        bundleId: "com.onix.flutter.firebase.auth.test.test_prj_ivan"
        icon: "flavor_assets/prod/launcher_icons/ic_launcher.png"





flutter_intl:
  enabled: true
  arb_dir: lib/app/localization/l10n
  output_dir: lib/app/localization/generated
  
#generated with mason